### ISSUE TITLE
License or permission information for repo

### ISSUE THREAD

**Issue by thailyn** [eebasso/Rimworld-Psychology-unofficial-v1.1-1.4#9]
Neither this repo nor the original code by the original author has any explicitly stated license or terms for derivative use. I asked the original author regarding this, and they said:

> Yes, anyone may do anything with my work as long as I am credited as the original mod author.

Source: the most recent comment on [this page](https://steamcommunity.com/id/epsilon-delta) as of this writing.

With this in mind, can you please share what your terms are for reusing your changes to the codebase on top of the original author's work? Do you allow derivative works? Thanks!

**Comment by eebasso** [comment]
Yes I allow derivative works. Giving me credit would be nice. I also like the idea of collaboration and centralization more than fragmentation. What did you have in mind? If you have some ideas, maybe you can make a PR and inspire me to get back into maintaining this mod.

**Comment by thailyn** [comment]
Thank you for the clarification, and, of course, I will give credit to you.

At the moment, I do not have specific long-term goals, though I have ideas I want to try out, experiments, etc. At the moment, I have been working locally on performance improvements and bug fixes, while trying to better understand how exactly the calculations and such in the mod works.

In general, I am also not against collaboration, but, it seemed to me that both this repo and the corresponding Steam workshop page were not really being maintained. The questions I posed in another [issue in this repo](https://github.com/eebasso/Rimworld-Psychology-unofficial-v1.1-1.4/issues/8#issuecomment-1705496333), as well as a similar post I made on the workshop page, have gone unanswered for months, so I have been seeing a fork as the easiest way to move forward, assuming I could get permission (and just using it myself without sharing if not).

**Comment by tk421storm** [comment]
@thailyn did you ever end up forking this repo? I was also looking into solving some long-standing bugs today. I definitely don't want to lose this mod once 1.5 comes out

**Comment by thailyn** [comment]
@tk421storm I have now created a GitHub fork. I had been just working with a local git repo, which I will push to there shortly. We can discuss specific issues and such there. I'm closing this bug now, as this repo's author has graciously responded to and resolved my initial request.
